/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bombe;


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bombe1 = new bombe.Bombe();
        bombe2 = new bombe.Bombe();
        bombe3 = new bombe.Bombe();
        bombe4 = new bombe.Bombe();
        bombe5 = new bombe.Bombe();
        bombe6 = new bombe.Bombe();
        bombe7 = new bombe.Bombe();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bombe Game");

        bombe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bombe1MouseClicked(evt);
            }
        });
        bombe1.addTempListener(new bombe.TempListener() {
            public void temp(bombe.TempEvent evt) {
                bombe1Temp(evt);
            }
        });

        bombe2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bombe2MouseClicked(evt);
            }
        });
        bombe2.addTempListener(new bombe.TempListener() {
            public void temp(bombe.TempEvent evt) {
                bombe2Temp(evt);
            }
        });

        bombe3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bombe3MouseClicked(evt);
            }
        });
        bombe3.addTempListener(new bombe.TempListener() {
            public void temp(bombe.TempEvent evt) {
                bombe3Temp(evt);
            }
        });

        bombe4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bombe4MouseClicked(evt);
            }
        });
        bombe4.addTempListener(new bombe.TempListener() {
            public void temp(bombe.TempEvent evt) {
                bombe4Temp(evt);
            }
        });

        bombe5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bombe5MouseClicked(evt);
            }
        });
        bombe5.addTempListener(new bombe.TempListener() {
            public void temp(bombe.TempEvent evt) {
                bombe5Temp(evt);
            }
        });

        bombe6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bombe6MouseClicked(evt);
            }
        });
        bombe6.addTempListener(new bombe.TempListener() {
            public void temp(bombe.TempEvent evt) {
                bombe6Temp(evt);
            }
        });

        bombe7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bombe7MouseClicked(evt);
            }
        });
        bombe7.addTempListener(new bombe.TempListener() {
            public void temp(bombe.TempEvent evt) {
                bombe7Temp(evt);
            }
        });

        jTextField1.setText("ETAT");

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
                jButton1ActionPerformed1(evt);
                jButton1ActionPerformed2(evt);
                jButton1ActionPerformed3(evt);
                jButton1ActionPerformed4(evt);
                jButton1ActionPerformed5(evt);
                jButton1ActionPerformed6(evt);
            }
        });

        jButton2.setText("RESTART");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
                jButton2ActionPerformed1(evt);
                jButton2ActionPerformed2(evt);
                jButton2ActionPerformed3(evt);
                jButton2ActionPerformed4(evt);
                jButton2ActionPerformed5(evt);
                jButton2ActionPerformed6(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(bombe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(bombe5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(31, 31, 31)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton1)))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bombe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bombe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(bombe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bombe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bombe7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bombe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bombe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bombe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bombe4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bombe5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bombe6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bombe7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        bombe6.restart();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed1
        bombe1.restart();
    }//GEN-LAST:event_jButton2ActionPerformed1

    private void jButton2ActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed2
        bombe4.restart();
    }//GEN-LAST:event_jButton2ActionPerformed2

    private void jButton2ActionPerformed3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed3
        bombe2.restart();
    }//GEN-LAST:event_jButton2ActionPerformed3

    private void jButton2ActionPerformed4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed4
        bombe5.restart();
    }//GEN-LAST:event_jButton2ActionPerformed4

    private void jButton2ActionPerformed5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed5
        bombe7.restart();
    }//GEN-LAST:event_jButton2ActionPerformed5

    private void jButton2ActionPerformed6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed6
        bombe3.restart();
    }//GEN-LAST:event_jButton2ActionPerformed6

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        bombe7.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed1
        bombe6.start();
    }//GEN-LAST:event_jButton1ActionPerformed1

    private void jButton1ActionPerformed2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed2
        bombe5.start();
    }//GEN-LAST:event_jButton1ActionPerformed2

    private void jButton1ActionPerformed3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed3
        bombe4.start();
    }//GEN-LAST:event_jButton1ActionPerformed3

    private void jButton1ActionPerformed4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed4
        bombe3.start();
    }//GEN-LAST:event_jButton1ActionPerformed4

    private void jButton1ActionPerformed5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed5
        bombe2.start();
    }//GEN-LAST:event_jButton1ActionPerformed5

    private void jButton1ActionPerformed6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed6
        bombe1.start();
    }//GEN-LAST:event_jButton1ActionPerformed6

    private void bombe1Temp(bombe.TempEvent evt) {//GEN-FIRST:event_bombe1Temp
        jTextField1.setText("ATTENTION BOMBE 1 !");
    }//GEN-LAST:event_bombe1Temp

    private void bombe2Temp(bombe.TempEvent evt) {//GEN-FIRST:event_bombe2Temp
        jTextField1.setText("ATTENTION BOMBE 2 !");
    }//GEN-LAST:event_bombe2Temp

    private void bombe3Temp(bombe.TempEvent evt) {//GEN-FIRST:event_bombe3Temp
        jTextField1.setText("ATTENTION BOMBE 3");
    }//GEN-LAST:event_bombe3Temp

    private void bombe4Temp(bombe.TempEvent evt) {//GEN-FIRST:event_bombe4Temp
        jTextField1.setText("ATTENTION BOMBE 4 !");
    }//GEN-LAST:event_bombe4Temp

    private void bombe5Temp(bombe.TempEvent evt) {//GEN-FIRST:event_bombe5Temp
        jTextField1.setText("ATTENTION BOMBE 5 !");
    }//GEN-LAST:event_bombe5Temp

    private void bombe6Temp(bombe.TempEvent evt) {//GEN-FIRST:event_bombe6Temp
        jTextField1.setText("ATTENTION BOMBE 6 !");
    }//GEN-LAST:event_bombe6Temp

    private void bombe7Temp(bombe.TempEvent evt) {//GEN-FIRST:event_bombe7Temp
        jTextField1.setText("ATTENTION BOMBE 7 !");
    }//GEN-LAST:event_bombe7Temp

    private void bombe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bombe1MouseClicked
        bombe1.onClick();
    }//GEN-LAST:event_bombe1MouseClicked

    private void bombe2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bombe2MouseClicked
        bombe2.onClick();
    }//GEN-LAST:event_bombe2MouseClicked

    private void bombe3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bombe3MouseClicked
        bombe3.onClick();
    }//GEN-LAST:event_bombe3MouseClicked

    private void bombe4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bombe4MouseClicked
        bombe4.onClick();
    }//GEN-LAST:event_bombe4MouseClicked

    private void bombe5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bombe5MouseClicked
        bombe5.onClick();
    }//GEN-LAST:event_bombe5MouseClicked

    private void bombe6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bombe6MouseClicked
        bombe6.onClick();
    }//GEN-LAST:event_bombe6MouseClicked

    private void bombe7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bombe7MouseClicked
        bombe7.onClick();
    }//GEN-LAST:event_bombe7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bombe.Bombe bombe1;
    private bombe.Bombe bombe2;
    private bombe.Bombe bombe3;
    private bombe.Bombe bombe4;
    private bombe.Bombe bombe5;
    private bombe.Bombe bombe6;
    private bombe.Bombe bombe7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
